HEADER = src/header.zsh

SRC_REST = src/utils.zsh \
           src/git-helpers.zsh \
           src/changelog.zsh \
           src/commands/idea.zsh \
           src/commands/issue.zsh \
           src/commands/snapshot.zsh \
           src/commands/propose.zsh \
           src/commands/port.zsh \
           src/commands/done.zsh \
           src/commands/prune.zsh \
           src/commands/init.zsh \
           src/main.zsh

SRC = $(HEADER) $(SRC_REST)

git-hack: $(SRC)
	{ head -n 1 $(HEADER); \
	  echo '# Generated from src/ — do not edit this file directly. Run: make'; \
	  tail -n +2 $(HEADER); \
	  cat $(SRC_REST); } > git-hack
	chmod +x git-hack

check:
	@for f in $(SRC); do zsh -n $$f && echo "ok: $$f"; done

test:
	@failed=0; \
	for f in tests/test_*.zsh; do \
	  echo "--- $$f ---"; \
	  zsh $$f || failed=$$((failed+1)); \
	done; \
	echo ""; \
	[ $$failed -eq 0 ] && echo "All tests passed." || { echo "$$failed test file(s) had failures."; exit 1; }

install-hooks:
	git config core.hooksPath .githooks
	@echo "Git hooks installed (core.hooksPath = .githooks)."

# Usage: make release VERSION=v0.1.0
release: git-hack
	@[ -n "$(VERSION)" ] || { echo "Usage: make release VERSION=v0.1.0"; exit 1; }
	git tag $(VERSION)
	git push origin $(VERSION)
	@echo ""
	@echo "Tag $(VERSION) pushed. Now:"
	@echo "  1. Create a GitHub Release from the tag:"
	@echo "     https://github.com/indemnity83/homebrew-git-hack/releases/new?tag=$(VERSION)"
	@echo "  2. Get the sha256:"
	@echo "     curl -sL https://github.com/indemnity83/homebrew-git-hack/archive/refs/tags/$(VERSION).tar.gz | shasum -a 256"
	@echo "  3. Update Formula/git-hack.rb with the new url and sha256."

.PHONY: check test install-hooks release
