HEADER = src/header.zsh

SRC_REST = src/utils.zsh \
           src/git-helpers.zsh \
           src/changelog.zsh \
           src/commands/idea.zsh \
           src/commands/issue.zsh \
           src/commands/commit.zsh \
           src/commands/propose.zsh \
           src/commands/ship.zsh \
           src/commands/pick.zsh \
           src/commands/done.zsh \
           src/commands/init.zsh \
           src/main.zsh

SRC = $(HEADER) $(SRC_REST)

git-hack: $(SRC)
	{ head -n 1 $(HEADER); \
	  echo '# Generated from src/ — do not edit this file directly. Run: make'; \
	  tail -n +2 $(HEADER); \
	  cat $(SRC_REST); } > git-hack
	chmod +x git-hack

check:
	@for f in $(SRC); do zsh -n $$f && echo "ok: $$f"; done

test:
	@failed=0; \
	for f in tests/test_*.zsh; do \
	  echo "--- $$f ---"; \
	  zsh $$f || failed=$$((failed+1)); \
	done; \
	echo ""; \
	[ $$failed -eq 0 ] && echo "All tests passed." || { echo "$$failed test file(s) had failures."; exit 1; }

install-hooks:
	git config core.hooksPath .githooks
	@echo "Git hooks installed (core.hooksPath = .githooks)."

doc/git-hack.1: doc/git-hack.1.ronn
	ronn --roff $<

man: doc/git-hack.1

.PHONY: check test install-hooks man
