name: Build (Release)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Upload git-hack script as release asset
        run: gh release upload ${{ github.event.release.tag_name }} git-hack --clobber
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload man page as release asset
        run: gh release upload ${{ github.event.release.tag_name }} doc/git-hack.1 --clobber
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
